In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [2]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Using GPU:{torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU.")

GPU is available!
Using GPU:Tesla T4


**Creating a Tensor**

In [3]:
# Using Empty
a = torch.empty(2,3)
a

tensor([[2.1715e-18, 6.7010e-10, 8.4953e+20],
        [4.2490e-05, 6.5262e-10, 2.0663e+20]])

In [4]:
# Check type
type(a)

torch.Tensor

In [5]:
# Using Zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# using rand
torch.rand(2,3)

tensor([[0.1532, 0.6159, 0.5500],
        [0.3529, 0.8657, 0.7203]])

In [11]:
# Use of seed
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [12]:
# Manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [13]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [14]:
# Using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
# Other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


Tensor Shapes

In [16]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
x.shape

torch.Size([2, 3])

In [18]:
torch.empty_like(x)

tensor([[                  0, 7310593858020254331, 3616445622929465956],
        [6068091618180738357, 4049081553018041648, 6499593895544043566]])

In [20]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [21]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [22]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

Tensor Data Types

In [23]:
# find data type
x.dtype

torch.int64

In [24]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [25]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [26]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

**Mathematical operations**

1. Scalar operation

In [27]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [28]:
# addition
x + 2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [29]:
# substraction
x - 2

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])

In [30]:
# multiplication
x * 3

tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])

In [31]:
# division
x / 3

tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])

In [32]:
# int division
(x * 100)//3

tensor([[23., 26.],
        [13., 30.]])

In [33]:
# mod
((x * 100)//3)%2

tensor([[1., 0.],
        [1., 0.]])

In [34]:
# power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

**2. Element wise operation**

In [35]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [36]:
# add
a + b

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

In [37]:
 # sub
a - b

tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])

In [38]:
# multiply
a * b

tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])

In [39]:
# division
a / b

tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])

In [40]:
# power
a ** b

tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])

In [41]:
# mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [42]:
c = torch.tensor([1, -2, 3, -4])

In [43]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [44]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [45]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [46]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [47]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [48]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [49]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [60]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[5., 7., 3.],
        [9., 4., 0.]])

In [51]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([15.,  9.])

In [52]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([4., 0., 8.])

In [53]:
# median
torch.median(e)

tensor(0.)

In [54]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [55]:
# product
torch.prod(e)

tensor(0.)

In [56]:
# standard deviation
torch.std(e)

tensor(4.4272)

In [57]:
# variance
torch.var(e)

tensor(19.6000)

In [61]:
# argmax
torch.argmax(e)

tensor(3)

In [62]:
# argmin
torch.argmin(e)

tensor(5)

4. Matrix operations

In [63]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 7, 5],
        [9, 9, 7]])
tensor([[5, 9],
        [8, 9],
        [7, 9]])


In [64]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[116, 153],
        [166, 225]])

In [65]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [66]:
# transpose
torch.transpose(f, 0, 1)

tensor([[5, 9],
        [7, 9],
        [5, 7]])

In [70]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 0., 4.],
        [3., 8., 8.],
        [3., 3., 5.]])

In [71]:
# determinant
torch.det(h)

tensor(20.0000)

In [72]:
# inverse
torch.inverse(h)

tensor([[ 0.8000,  0.6000, -1.6000],
        [ 0.4500,  0.6500, -1.4000],
        [-0.7500, -0.7500,  2.0000]])

5. Comparison operations

In [73]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[0, 6, 4],
        [0, 8, 4]])
tensor([[7, 2, 3],
        [8, 5, 6]])


In [74]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])

6. Special functions

In [75]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[2., 9., 5.],
        [0., 4., 2.]])

In [76]:
# log
torch.log(k)

tensor([[0.6931, 2.1972, 1.6094],
        [  -inf, 1.3863, 0.6931]])

In [77]:
# exp
torch.exp(k)

tensor([[7.3891e+00, 8.1031e+03, 1.4841e+02],
        [1.0000e+00, 5.4598e+01, 7.3891e+00]])

In [78]:
# sqrt
torch.sqrt(k)

tensor([[1.4142, 3.0000, 2.2361],
        [0.0000, 2.0000, 1.4142]])

In [79]:
# sigmoid
torch.sigmoid(k)

tensor([[0.8808, 0.9999, 0.9933],
        [0.5000, 0.9820, 0.8808]])

In [80]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.8808, 0.9933, 0.9526],
        [0.1192, 0.0067, 0.0474]])

In [81]:
# relu
torch.relu(k)

tensor([[2., 9., 5.],
        [0., 4., 2.]])

Inplace Operations

In [82]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.7668, 0.1659, 0.4393],
        [0.2243, 0.8935, 0.0497]])
tensor([[0.1780, 0.3011, 0.1893],
        [0.9186, 0.2131, 0.3957]])


In [83]:
m.add_(n)

tensor([[0.9448, 0.4670, 0.6286],
        [1.1429, 1.1066, 0.4454]])

In [84]:
m

tensor([[0.9448, 0.4670, 0.6286],
        [1.1429, 1.1066, 0.4454]])

In [85]:
n

tensor([[0.1780, 0.3011, 0.1893],
        [0.9186, 0.2131, 0.3957]])

In [86]:
torch.relu(m)

tensor([[0.9448, 0.4670, 0.6286],
        [1.1429, 1.1066, 0.4454]])

In [87]:
m.relu_()

tensor([[0.9448, 0.4670, 0.6286],
        [1.1429, 1.1066, 0.4454]])

In [88]:
m

tensor([[0.9448, 0.4670, 0.6286],
        [1.1429, 1.1066, 0.4454]])

Copying a Tensor

In [89]:
a = torch.rand(2,3)
a

tensor([[0.6017, 0.4234, 0.5224],
        [0.4175, 0.0340, 0.9157]])

In [90]:
b = a

In [91]:
b

tensor([[0.6017, 0.4234, 0.5224],
        [0.4175, 0.0340, 0.9157]])

In [92]:
a[0][0] = 0

In [93]:
a

tensor([[0.0000, 0.4234, 0.5224],
        [0.4175, 0.0340, 0.9157]])

In [94]:
b

tensor([[0.0000, 0.4234, 0.5224],
        [0.4175, 0.0340, 0.9157]])

In [95]:
id(a)

139550318702672

In [96]:
id(b)

139550318702672

In [97]:
b = a.clone()

In [98]:
a

tensor([[0.0000, 0.4234, 0.5224],
        [0.4175, 0.0340, 0.9157]])

In [99]:
b

tensor([[0.0000, 0.4234, 0.5224],
        [0.4175, 0.0340, 0.9157]])

In [100]:
a[0][0] = 10

In [101]:
a

tensor([[10.0000,  0.4234,  0.5224],
        [ 0.4175,  0.0340,  0.9157]])

In [102]:
b

tensor([[0.0000, 0.4234, 0.5224],
        [0.4175, 0.0340, 0.9157]])

In [103]:
id(a)

139550318702672

In [104]:
id(b)

139550318698448